mybatis:
    type-aliases-package: com.codervibe.rizhi.model
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/sdaily?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
        password: admin
        username: root
    mvc:
        static-path-pattern: /**
    resources:
        static-locations: classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/
    thymeleaf:
        cache: false
